name: DigitalSeer
favicon: null
layout_spectrum: 0.7806000092532486
typography_spectrum: 0.16217950987629592
title: blog.dimitrigarcia.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.14724780432879925
  lightness: 0.9136994534637779
  saturation: 0.9845997733063996
  rhythmicContrast: 0.38424636889249086
purpose: []
